version: '3'
services:
  web:
    image: webdevops/php-apache-dev:7.3
    container_name: web
    restart: always
    user: application
    environment:
      - WEB_ALIAS_DOMAIN=localhost
      - WEB_DOCUMENT_ROOT=/app/pub
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=4096M
      - PHP_MAX_EXECUTION_TIME=900
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
    volumes:
      - .:/app:cached
    ports:
      - "80:80"
      - "443:443"
      - "32823:22"
    links:
      - mysql
      - elasticsearch
    depends_on:
      - mysql
      - phpmyadmin
      - elasticsearch

  mysql:
    image: mariadb:10.2
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
    volumes:
      - mysql:/var/lib/mysql

  elasticsearch:
    container_name: elasticsearch
    image: docker.io/bitnami/elasticsearch:6
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node
      - bootstrap.memory_lock= true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 512m
    volumes:
      - elasticsearch:/bitnami/elasticsearch/data
    ports:
      - 9200:9200

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
    links:
      - mysql:db
    depends_on:
      - mysql

volumes:
  mysql:
    driver: local
  elasticsearch:
    driver: local
